modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "viscord"
version = "${version}"
displayName = "Viscord"
authors = "Me!"
description = '''
A standalone Discord integration for Minecraft servers, porting the Discord capabilities from VonixCore.
'''
#logoFile = ""

[[dependencies.viscord]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.viscord]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.viscord]]
modId = "architectury"
mandatory = true
versionRange = "[4.12.94,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "viscord-platform.mixins.json"
