modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "viscord"
version = "${version}"
displayName = "Viscord"
authors = "Me!"
description = '''
A standalone Discord integration for Minecraft servers, porting the Discord capabilities from VonixCore.
'''
#logoFile = ""

[[dependencies.viscord]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.viscord]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.viscord]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
