modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "viscord"
version = "${version}"
displayName = "Viscord"
authors = "Me!"
description = '''
A standalone Discord integration for Minecraft servers, porting the Discord capabilities from VonixCore.
'''
#logoFile = ""

[[dependencies.viscord]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.viscord]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.viscord]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "viscord-platform.mixins.json"
