modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "viscord"
version = "${version}"
displayName = "Viscord"
authors = "Vonix Network"
description = '''Server-side bidirectional chat integration for Discord and Fluxer.'''
#logoFile = ""

[[dependencies.viscord]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.viscord]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.viscord]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "SERVER"

[[mixins]]
config = "viscord-platform.mixins.json"

[modProperties]
eventBus.excludedPackages = "network.vonix.viscord.shadow"
