modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "viscord"
version = "${version}"
displayName = "Viscord"
authors = "Me!"
description = '''
A standalone Discord integration for Minecraft servers, porting the Discord capabilities from VonixCore.
'''
#logoFile = ""

[[dependencies.viscord]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.viscord]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.viscord]]
modId = "architectury"
mandatory = true
versionRange = "[6.6.92,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "viscord-platform.mixins.json"
